module mchange.commons.java {
    requires java.management;

    requires transitive java.desktop;
    requires transitive java.logging;
    requires transitive java.naming;
    requires transitive java.rmi;
    requires transitive java.sql;
    requires transitive java.xml;

    exports com.mchange.io;
    exports com.mchange.io.impl;
    exports com.mchange.lang;
    exports com.mchange.net;
    exports com.mchange.rmi;
    exports com.mchange.util;
    exports com.mchange.util.impl;
    exports com.mchange.v1.cachedstore;
    exports com.mchange.v1.db.sql;
    exports com.mchange.v1.db.sql.schemarep;
    exports com.mchange.v1.db.sql.xmlpropsschema;
    exports com.mchange.v1.identicator;
    exports com.mchange.v1.identicator.test;
    exports com.mchange.v1.io;
    exports com.mchange.v1.jvm;
    exports com.mchange.v1.lang;
    exports com.mchange.v1.lang.holders;
    exports com.mchange.v1.util;
    exports com.mchange.v1.xml;
    exports com.mchange.v1.xmlprops;
    exports com.mchange.v2.async;
    exports com.mchange.v2.async.test;
    exports com.mchange.v2.beans;
    exports com.mchange.v2.beans.swing;
    exports com.mchange.v2.cfg;
    exports com.mchange.v2.cmdline;
    exports com.mchange.v2.coalesce;
    exports com.mchange.v2.codegen;
    exports com.mchange.v2.codegen.bean;
    exports com.mchange.v2.codegen.intfc;
    exports com.mchange.v2.collection;
    exports com.mchange.v2.csv;
    exports com.mchange.v2.debug;
    exports com.mchange.v2.encounter;
    exports com.mchange.v2.holders;
    exports com.mchange.v2.io;
    exports com.mchange.v2.lang;
    exports com.mchange.v2.lang.reflect;
    exports com.mchange.v2.lock;
    exports com.mchange.v2.log;
    exports com.mchange.v2.log.jdk14logging;
    exports com.mchange.v2.log.log4j;
    exports com.mchange.v2.log.log4j2;
    exports com.mchange.v2.log.slf4j;
    exports com.mchange.v2.management;
    exports com.mchange.v2.naming;
    exports com.mchange.v2.net;
    exports com.mchange.v2.reflect;
    exports com.mchange.v2.ser;
    exports com.mchange.v2.sql;
    exports com.mchange.v2.sql.filter;
    exports com.mchange.v2.uid;
    exports com.mchange.v2.util;
    exports com.mchange.v3.concurrent;
    exports com.mchange.v3.decode;
    exports com.mchange.v3.filecache;
    exports com.mchange.v3.hocon;
    exports com.mchange.v3.nio;

}
